### ISSUE TITLE
Glottolog mappings

### ISSUE THREAD

**Issue by natalia-morozova** [lexibank/sohartmannchin#1]
- I would suggest linking Chinbon to chin1478 / cnb and leave Nyhmoye unmapped (similarly to [STEDT](http://stedt.berkeley.edu/~stedt-cgi/rootcanal.pl/group/69/1948)).

- Another issue concerns Daai and Mkaang: both are mapped to [daai1236](https://glottolog.org/resource/languoid/id/daai1236), most likely because one of the alternative names of Daai is M'kaang. However, the lists differ a lot (compare [Daai](http://stedt.berkeley.edu/~stedt-cgi/rootcanal.pl/gnis?lexicon.lgid=1953) and [Mkaang](http://stedt.berkeley.edu/~stedt-cgi/rootcanal.pl/gnis?lexicon.lgid=1953)). Unfortunately, I don't have access to the original paper, so I might only suggest that Mkaang is [Lamkang](https://glottolog.org/resource/languoid/id/lamk1238).

- Since [khum1250](https://glottolog.org/resource/languoid/id/khum1250) is a bookkeeping entry, Wakung should probably be re-mapped to [mroc1235](https://glottolog.org/resource/languoid/id/mroc1235).

**Comment by LinguList** [comment]
Okay, I think this is reasonable. Linking just followed stedt mostly, and they give the same iso-code for daai and mkaang. But re-linking it is probably useful, specifically as long as we lack the original source.

**Comment by chrzyki** [comment]
Done in https://github.com/lexibank/sohartmannchin/commit/b97246e4b13f9764431698a73feac08123958e9e.
